name: Push QA

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: htg-qa-strapi-app
  REGISTRY_LOGIN_SERVER: htgqaregistry.azurecr.io

jobs:
    build-and-deploy:
        if: github.actor == 'JamesChristianson' || github.actor == 'emailtokvk' || github.actor == 'thomaslkp123' || github.actor == 'rajchala' || github.actor == 'TasTasniem'
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_QA_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_QA_USERNAME }}
            password: ${{ secrets.REGISTRY_QA_PASSWORD }}
        - run: |
            docker build . -t ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }} -t ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:latest
            docker push ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.AZURE_WEBAPP_NAME }} --all-tags
        - name: 'Deploy to App Service'
          uses: azure/webapps-deploy@v2
          with:
            app-name: '${{ env.AZURE_WEBAPP_NAME }}'
            images: '${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}'
        - name: Azure logout
          run: |
            az logout
