name: Push uat-dr

on:
  push:
    branches:
      - uat

env:
  AZURE_WEBAPP_NAME: htg-druat-strapi-app
  AZURE_WEBAPP_RG: htg-druat-strapi-rg  
  REGISTRY_LOGIN_SERVER: htgdruatregistry.azurecr.io

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_UAT_CREDENTIALS }}
        - run: |
            ./AppSettingsLoad.ps1 '${{ env.AZURE_WEBAPP_NAME }}' '${{ env.AZURE_WEBAPP_RG }}'
          shell: pwsh            
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_UAT_USERNAME }}
            password: ${{ secrets.REGISTRY_UAT_PASSWORD }}
        - run: |
            docker build . -t ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }} -t ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:latest
            docker push ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.AZURE_WEBAPP_NAME }} --all-tags
        - name: 'Deploy to App Service'
          uses: azure/webapps-deploy@v2
          with:
            app-name: '${{ env.AZURE_WEBAPP_NAME }}'
            images: '${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}'
        - name: Azure logout
          run: |
            az logout
